### ISSUE TITLE
Which LICENSE do we go with?

### ISSUE THREAD

**Issue by istx25** [cosmiclabsio/ConfidenceKit#2]
We need to decide on which license to use for [ConfidenceKit](https://github.com/cosmiclabsio/ConfidenceKit). We need to protect our codebase from being stolen/used-without-credit, but easily allow anyone to use the framework accordingly.

What license do you think we should go for, @damonjones?

**Comment by istx25** [comment]
> OpenCV is released under a BSD license and hence it’s free for both academic and commercial use. It has C++, C, Python and Java interfaces and supports Windows, Linux, Mac OS, iOS and Android. OpenCV was designed for computational efficiency and with a strong focus on real-time applications. Written in optimized C/C++, the library can take advantage of multi-core processing. Enabled with OpenCL, it can take advantage of the hardware acceleration of the underlying heterogeneous compute platform. Adopted all around the world, OpenCV has more than 47 thousand people of user community and estimated number of downloads exceeding 9 million. Usage ranges from interactive art, to mines inspection, stitching maps on the web or through advanced robotics.

**Comment by damonjones** [comment]
The ISC license is functionally equivalent to the BSD 2-Clause and MIT licenses, removing some language that is no longer necessary.

**Comment by istx25** [comment]
Okay, awesome. :+1:
